CREATE DATABASE AVALIACAO;
USE AVALIACAO;

CREATE TABLE PRO_PRODUTO(
	PRO_ID				INT(13) 	NOT NULL,
	PRO_NOME			VARCHAR(30) NOT NULL,
    PRO_ESPECIFICACAO   VARCHAR(100) NOT NULL,
	PRO_VALOR		    INT(4) NOT NULL,
	CONSTRAINT PRO_PK PRIMARY KEY (PRO_ID)
	);
    
